[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["venv", "alembic", "docker", ".git", "__pycache__", ".env"]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E203", "E266", "E501"]

[tool.ruff.format]
quote-style = "double"
